name: GitHub Contributions Snake

on:
  schedule:
    - cron: '0 0 * * *' # se ejecuta diario
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: Pipetboy   # <-- tu usuario
